import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";

import { registerBackupSiteTool } from "./backup-site.js";
import { registerCleanupBackupsTool } from "./cleanup-backups.js";
import { registerDbExportTool } from "./db-export.js";
import { registerDbImportTool } from "./db-import.js";
import { registerDeleteBackupTool } from "./delete-backup.js";
import { registerDeleteSiteFileTool } from "./delete-site-file.js";
import { registerExecuteWpCliTool } from "./execute-wp-cli.js";
import { registerListBackupsTool } from "./list-backups.js";
import { registerListSiteFilesTool } from "./list-site-files.js";
import { registerLocalDoctorTool } from "./local-doctor.js";
import { registerLocalEnvironmentCheckTool } from "./local-environment-check.js";
import { registerLocalLogsTool } from "./local-logs.js";
import { registerListLocalSitesTool } from "./list-local-sites.js";
import { registerLocalSiteInfoTool } from "./local-site-info.js";
import { registerMysqlExecuteTool } from "./mysql-execute.js";
import { registerMysqlQueryTool } from "./mysql-query.js";
import { registerMysqlSchemaTool } from "./mysql-schema.js";
import { registerPreviewRestoreBackupTool } from "./preview-restore-backup.js";
import { registerReadSiteFileTool } from "./read-site-file.js";
import { registerRestartLocalSiteTool } from "./restart-local-site.js";
import { registerRestoreBackupTool } from "./restore-backup.js";
import { registerSearchSiteFilesTool } from "./search-site-files.js";
import { registerStartLocalSiteTool } from "./start-local-site.js";
import { registerStopLocalSiteTool } from "./stop-local-site.js";
import { registerWriteSiteFileTool } from "./write-site-file.js";

export function registerTools(server: McpServer) {
  registerListLocalSitesTool(server);
  registerStartLocalSiteTool(server);
  registerStopLocalSiteTool(server);
  registerRestartLocalSiteTool(server);
  registerLocalEnvironmentCheckTool(server);
  registerLocalDoctorTool(server);
  registerLocalLogsTool(server);
  registerLocalSiteInfoTool(server);
  registerListSiteFilesTool(server);
  registerReadSiteFileTool(server);
  registerSearchSiteFilesTool(server);
  registerWriteSiteFileTool(server);
  registerDeleteSiteFileTool(server);
  registerBackupSiteTool(server);
  registerListBackupsTool(server);
  registerDeleteBackupTool(server);
  registerCleanupBackupsTool(server);
  registerDbExportTool(server);
  registerDbImportTool(server);
  registerPreviewRestoreBackupTool(server);
  registerRestoreBackupTool(server);
  registerMysqlQueryTool(server);
  registerMysqlExecuteTool(server);
  registerMysqlSchemaTool(server);
  registerExecuteWpCliTool(server);
}
